### ISSUE TITLE
The results are not very stable.

### ISSUE THREAD

**Issue by konanzheng** [adslbarxatov/FontFinder#1]
Has the algorithm been improved? According to the proportion of pixel lattices, it seems that it is not stable.When recognizing Chinese fonts, 99% of clearly incorrect fonts are prompted.

**Comment by adslbarxatov** [comment]
Hello, dear user!

At first: thank you for the first bug report in our history! We've really thought that nobody using our solutions. It is really important for us to see that somebody wants to help us in our work. And we'll apply all possible efforts to solve your inconvenience!

At second: we've never perform tests on chinese fonts (and any other fonts except of EN_US, RU_RU and compatible ones). We need some time to find where this bug comes from. But it will be beautiful if you will specify names of fonts and attach a picture sample that you got troubles on.

Thank you very much for creating this thread!
Best regards,
Nicolay B.

**Comment by adslbarxatov** [comment]
Issue closed due to confirmation absence

Best regards,
Nicolay B.
